# Generated by Django 3.2.12 on 2023-05-19 14:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kb'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to=api.models.imgsave)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='KB',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
