# Generated by Django 3.2.12 on 2023-05-20 09:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230519_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(upload_to=(api.models.imgsave, 'profile_images')),
        ),
    ]
