# Generated by Django 3.2.12 on 2023-05-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar',
            field=models.CharField(default='XXXXXXXXXXX', max_length=20),
        ),
    ]
