# Generated by Django 4.2.1 on 2023-05-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_category_categoreylogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
