# Generated by Django 4.2.1 on 2023-05-30 14:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='up', upload_to=api.models.imgsave),
        ),
    ]
