# Generated by Django 4.2.1 on 2023-05-30 14:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_user_profile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default=2, upload_to=api.models.imgsave),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
